site_name: SuperBill-Document
theme:
  name: material
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Cancelled Sale: Cancelled Sale.md
  - Composition Scheme Impact: Composition Scheme Impact.md
  - Delivery Challan: Delivery Challan.md
  - Estimate: Estimate.md
  - Expense: Expense.md
  - ITC & Reverse Charge: ITC-ReverseCharge.md
  - Purchase Invoice: Purchase Invoice.md
  - Purchase Order: Purchase Order.md
  - Purchase Return: Purchase Return.md
  - Sale Invoice: Sale Invoice.md
  - Sale Order: Sale Order.md
  - Sale Return: Sale Return.md